version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  default:

services:

  prometheus:
    image: napnap75/rpi-prometheus:prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--log.level=debug'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=10d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - "node_exporter:172.17.0.1"
      - "mobindi:172.17.0.1"

  node_exporter:
    image: prom/node-exporter:v1.0.1
    restart: unless-stopped
    ports:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # Linaro specific fix : thermal zone 0 is broken. Replace by thermal zone 1
      - /sys/class/thermal/thermal_zone1:/host/sys/class/thermal/thermal_zone0:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.wifi'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - --web.listen-address=:9100
    network_mode: host

  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - default
    ports:
      - 127.0.0.1:3010:3010
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - config.monitoring

