version: '2'

volumes:
  victoriametrics_data: {}
  vmagent_data: {}
  grafana_data: {}
  
networks:
  default:

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.101.0 
    restart: unless-stopped
    ports:
      - 8428:8428
    networks:
      - default
    volumes:
      - victoriametrics_data:/victoria-metrics-data
    command: [ "-retentionPeriod=${RETENTION:-31d}" ]
    deploy:
      mode: replicated
      replicas: 1

  vmagent:
    image: victoriametrics/vmagent:v1.101.0
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "vmagent_data:/var/vmagent"
      - "./scrape-config:/vmagent-conf:ro"
    command:
      - "-remoteWrite.url=${REMOTEWRITE_URL:-http://victoria-metrics:8428/api/v1/write}"
      - "-remoteWrite.tmpDataPath=/var/vmagent"
      - "-remoteWrite.forceVMProto=true"
      - "-remoteWrite.label"
      - "host=${HOSTNAME?missing hostname}"
      - "-remoteWrite.maxDiskUsagePerURL=500MB"
      - "-memory.allowedBytes=${MAX_VMAGENT_MEMORY:-128MB}"
      - "-promscrape.config=/vmagent-conf/${SCRAPE_CONFIG:-default.yml}"
      # Required to allow vmalert options
      - "-promscrape.config.strictParse=false"
    extra_hosts:
      - "node_exporter:172.17.0.1"
      - "mobindi:172.17.0.1"
      
  node_exporter:
    image: prom/node-exporter:v1.0.1
    restart: unless-stopped
    ports:
      - 172.17.0.1:9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.wifi'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - --web.listen-address=:9100
    network_mode: host

  grafana:
    image: grafana/grafana:10.4.2
#    depends_on:
#      - prometheus
    restart: unless-stopped
    networks:
      - default
    ports:
      - 127.0.0.1:3010:3010
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - config.monitoring

