# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #    monitor: 'rpi-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - 'alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  #- job_name: 'prometheus'
  #  # Override the global default and scrape targets from this job every 5 seconds.
  #  scrape_interval: 15s
  #  # metrics_path defaults to '/metrics'
  #  # scheme defaults to 'http'.
  #  static_configs:
  #    - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['node_exporter:9100']

#  - job_name: 'mobindi'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['mobindi:8080']

